Repository ignite-hq/web, pull requests merged in 2022-02, with the labels that each got.

#196 Add system bar component
  packages/vue/package-lock.json
  packages/vue/package.json
  packages/vue/src/components/SpNavbar/SpNavbar.vue
  packages/vue/src/components/SpSystemBar/SpSystemBar.vue
  packages/vue/src/components/SpSystemBar/index.ts
  packages/vue/src/components/index.ts
  packages/vue/src/composables/index.ts
  packages/vue/src/composables/useAccount.ts
  packages/vue/src/composables/useAddress.ts
  packages/vue/src/composables/useTxs.ts
Labels: feature-request

#209 #199: Remove the CRUD model from template
  packages/template/src/views/Data.vue
Labels: enhancement

#229 fix: Inputs UI improvements and selected tokens distance
  packages/vue/src/components/SpAmountSelect/SpAmountSelect.vue
  packages/vue/src/components/SpCrudUpdate/SpCrudUpdate.vue
  packages/vue/src/components/SpModal/SpModal.vue
  packages/vue/src/styles/_utility.scss
Labels: enhancement

#228 fix: Disabled create CRUD button if not logged in
  packages/vue/src/components/SpCrud/SpCrud.vue
Labels: enhancement

#227 feat: Use CRUD itemName for create button
  packages/vue/src/components/SpCrud/SpCrud.vue
Labels: enhancement

#226 fix: Add back and title for account dropdown
  packages/vue/src/components/SpAccDropdown/SpAccDropdown.vue
Labels: enhancement

#214 fix: Capitalize the itemName
  packages/vue/src/components/SpCrud/SpCrud.vue
Labels: enhancement

#237 fix: skeleton forever
  packages/vue/src/composables/useAssets.ts
Labels: enhancement

#239 feat: Add slot to override navbar logo
  packages/vue/src/components/SpNavbar/SpNavbar.vue
Labels: noteworthy

#250 fix: search position
  packages/vue/src/components/SpAssets/SpAssets.vue
Labels: enhancement
